## BRING SCAN TIME DOWN!!! ##


## GET ALL SORT / LIST OPTIONS TO IGNORE LOWER CASE and/or SPECIAL CHARS (Maybe?) ##


## ERRORS - EXCEPTIONS HANDLING (E.G. INCORRECT USER INPUT), GUESSIT OR PYMEDIAINFO MIS-HITS OR FALSE +'S ##
