## BRING SCAN TIME DOWN!!! ##


## GET ALL SORT / LIST OPTIONS TO IGNORE LOWER CASE and/or SPECIAL CHARS (Maybe?) ##


## ADD ASCIIPLOT OR TERMGRAPH (SOME TERMINAL GRAPHER) AS GRAPHING OPTIONS IN LMI ##


## COMPARISONS OF MEDIA-INDICES, GET LISTS FOR: 1) HAVE, 2) DO NOT HAVE, 3) HAVE BUT DIFFERENT ##


## ERRORS - EXCEPTIONS HANDLING (E.G. INCORRECT USER INPUT), GUESSIT OR PYMEDIAINFO MIS-HITS OR FALSE +'S ##


