## GET ALL SORT / LIST OPTIONS TO IGNORE LOWER CASE and/or SPECIAL CHARS (Maybe?) ##


## ADD ASCIIPLOT OR TERMGRAPH (SOME TERMINAL GRAPHER) AS GRAPHING OPTION LMI ##


## GRAB MEDIA-INFO FROM MOVIES AND TV WITH PYMEDIAINFO, SORT TO LISTS / DISPLAY, ADD TO LMI ##


## DO RESOLUTION TOTAL GRAPH CODE FOR TV SHOWS, ADD MOVIES AND TV RESOLUTIONS GRAPHS TO LMI ##


## ADD FEATURE TO DISPLAY TOTALS OF BOTH MOVIES AND TV SHOWS BY DECADE ##


## CREATE INDEX FOR MOVIES WITH DIR'S LIKE TV AS STRINGS FOR PYMEDIAINFO ##