## GET ALL SORT / LIST OPTIONS TO IGNORE LOWER CASE and/or SPECIAL CHARS (Maybe?) ##


## SCRAPE TV SHOW EPISODES FOR TITLE, YEAR, RES, PART, FILETYPE INFO ##


## ADD TERMGRAPH AS GRAPHING OPTION LMI ##


## TESTING TO GET GUESSIT OPTIONS TO PUSH TO LIST CATEGORIES FOR LATER SORTING / DISPLAY ##
